version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: full-stack-lab-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: fullstacklab
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge